---
plugin: amazon.aws.aws_ec2 
aws_profile: default # name of aws configuration 
regions:
  - us-east-1
filters:
  instance-state-name: running
  tag:Name:
    - Ubuntu
    - Amazon2
keyed_groups:
  - key: tags
    prefix: tag